# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

# TODO: Replace with your production app's client_id from Shopify Partner Dashboard
client_id = "2195b1a88a0850d56db2bb1d7e3f1f94"
name = "superupsell"
application_url = "https://superupsell.vercel.app"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "orders/paid" ]
  uri = "/webhooks/orders/paid"

[access_scopes]
scopes = "write_products,write_discounts,read_orders"

[app_proxy]
url = "https://superupsell.vercel.app/api"
subpath = "superupsell"
prefix = "apps"

[auth]
redirect_urls = [ "https://superupsell.vercel.app/api/auth" ]
